server:
  port: 9090
  servlet:
    context-path: /one

#alibaba的druid数据库连接池配置
spring:
    datasource:
      dynamic:
        primary: master
        datasource:
          master:
            driver-class-name: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/spb_one?useUnicode=true&characterEncoding=utf8   #master库
            username: root
            password: 123456
          slave:
            driver-class-name: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8   #从库
            username: root
            password: 123456
         #slave_2:
         #  driver-class-name: com.mysql.jdbc.Driver
         #  type: com.alibaba.druid.pool.DruidDataSource
         #  url: jdbc:mysql://localhost:3306/xxxx?useUnicode=true&characterEncoding=utf8   #数据源3
         #  username: root
         #  password: 123456
    aop:
      proxy-target-class: true

logging:
  config: classpath:logback.xml



mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapping/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


one:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    #项目名
    projectName: /one
    # 后端免认证接口 url
    anonUrl: /swagger-resources,/v2/**,/webjars/**,/login,/logout/**,/regist,/user/check/**,/doc.html,/getCaptcha,/test,/sale/**,/amount/**,/report/**,/park/**
    # token有效期，单位秒
    jwtTimeOut: 86400